let a  = [
  `JS Tutorial`,
  `JS HOME`,
  `JS Introduction`,
  `JS Where To`,
  `JS Output`,
  `JS Statements`,
  `JS Syntax`,
  `JS Comments`,
  `JS Variables`,
  `JS Let`,
  `JS Const`,
  `JS Operators`,
  `JS Arithmetic`,
  `JS Assignment`,
  `JS Data Types`,
  `JS Functions`,
  `JS Objects`,
  `JS Events`,
  `JS Strings`,
  `JS String Methods`,
  `JS String Search`,
  `JS String Templates`,
  `JS Numbers`,
  `JS BigInt`,
  `JS Number Methods`,
  `JS Number Properties`,
  `JS Arrays`,
  `JS Array Methods`,
  `JS Array Sort`,
  `JS Array Iteration`,
  `JS Array Const`,
  `JS Dates`,
  `JS Date Formats`,
  `JS Date Get Methods`,
  `JS Date Set Methods`,
  `JS Math`,
  `JS Random`,
  `JS Booleans`,
  `JS Comparisons`,
  `JS If Else`,
  `JS Switch`,
  `JS Loop For`,
  `JS Loop For In`,
  `JS Loop For Of`,
  `JS Loop While`,
  `JS Break`,
  `JS Iterables`,
];
console.log(a.length)